/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/naver/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 네이버 OAuth 로그인 URL
         * @description 네이버 OAuth 인증 페이지로 리다이렉트할 URL을 반환합니다.
         */
        get: operations["getNaverLoginUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/naver/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 네이버 OAuth 콜백
         * @description 네이버 OAuth 인증 완료 후 콜백을 처리하고 JWT 토큰을 발급합니다.
         */
        get: operations["naverCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google OAuth 로그인 URL
         * @description Google OAuth 인증 페이지로 리다이렉트할 URL을 반환합니다.
         */
        get: operations["getGoogleLoginUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google OAuth 콜백
         * @description Google OAuth 인증 완료 후 콜백을 처리하고 JWT 토큰을 발급합니다.
         */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 게스트 로그인
         * @description 게스트 계정을 즉시 생성하고 JWT 토큰을 발급합니다. OAuth 인증 없이 바로 서비스를 체험할 수 있습니다.
         */
        post: operations["guestLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 갱신
         * @description Refresh token으로 새 access token을 발급받습니다.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 현재 세션을 종료합니다 (refresh token 무효화).
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 사용자 정보
         * @description 현재 로그인한 사용자의 정보를 조회합니다.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 팀 목록
         * @description 현재 사용자가 속한 팀 목록을 조회합니다.
         */
        get: operations["listMyTeams"];
        put?: never;
        /**
         * 팀 생성
         * @description 새로운 팀을 생성합니다. 생성자는 자동으로 owner가 됩니다.
         */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{teamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 상세 조회
         * @description 팀 상세 정보를 조회합니다. 팀 멤버만 조회 가능합니다.
         */
        get: operations["getTeam"];
        /**
         * 팀 수정
         * @description 팀 정보를 수정합니다. owner 또는 admin만 수정 가능합니다.
         */
        put: operations["updateTeam"];
        post?: never;
        /**
         * 팀 삭제
         * @description 팀을 삭제합니다. owner만 삭제 가능합니다.
         */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{teamId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 멤버 목록
         * @description 팀의 멤버 목록을 조회합니다. 팀 멤버만 조회 가능합니다.
         */
        get: operations["listTeamMembers"];
        put?: never;
        /**
         * 팀 멤버 초대
         * @description 팀에 새로운 멤버를 초대합니다. owner 또는 admin만 초대 가능합니다.
         */
        post: operations["inviteTeamMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{teamId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 멤버 역할 수정
         * @description 팀 멤버의 역할을 수정합니다. owner만 수정 가능합니다.
         */
        put: operations["updateTeamMemberRole"];
        post?: never;
        /**
         * 멤버 제거
         * @description 팀에서 멤버를 제거합니다. owner 또는 admin만 제거 가능합니다. 자신을 제거하는 것은 항상 가능합니다.
         */
        delete: operations["removeTeamMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{teamId}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 회의 목록
         * @description 팀의 회의 목록을 조회합니다.
         */
        get: operations["listTeamMeetings"];
        put?: never;
        /**
         * 회의 생성
         * @description 팀에 새로운 회의를 생성합니다. 생성자는 자동으로 host가 됩니다.
         */
        post: operations["createMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회의 상세 조회
         * @description 회의 상세 정보를 조회합니다. 팀 멤버만 조회 가능합니다.
         */
        get: operations["getMeeting"];
        /**
         * 회의 수정
         * @description 회의 정보를 수정합니다. host 또는 팀 owner/admin만 수정 가능합니다.
         */
        put: operations["updateMeeting"];
        post?: never;
        /**
         * 회의 삭제
         * @description 회의를 삭제합니다. host 또는 팀 owner/admin만 삭제 가능합니다.
         */
        delete: operations["deleteMeeting"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회의 참여자 목록
         * @description 회의의 참여자 목록을 조회합니다. 팀 멤버만 조회 가능합니다.
         */
        get: operations["listMeetingParticipants"];
        put?: never;
        /**
         * 회의 참여자 추가
         * @description 회의에 새로운 참여자를 추가합니다. host만 추가 가능합니다. 해당 팀의 멤버만 추가할 수 있습니다.
         */
        post: operations["addMeetingParticipant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/participants/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 참여자 역할 수정
         * @description 회의 참여자의 역할을 수정합니다. host만 수정 가능합니다.
         */
        put: operations["updateMeetingParticipantRole"];
        post?: never;
        /**
         * 참여자 제거
         * @description 회의에서 참여자를 제거합니다. host만 제거 가능합니다. 자신을 제거하는 것은 항상 가능합니다.
         */
        delete: operations["removeMeetingParticipant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회의실 정보 조회
         * @description 실시간 회의에 필요한 정보를 조회합니다.
         *     - 현재 참여 중인 사용자 목록
         *     - ICE 서버 설정
         *     - 최대 참여자 수
         */
        get: operations["getMeetingRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회의 시작
         * @description 회의를 시작합니다. host만 시작 가능합니다.
         *     회의 상태가 scheduled -> ongoing으로 변경됩니다.
         */
        post: operations["startMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회의 종료
         * @description 회의를 종료합니다. host만 종료 가능합니다.
         *     회의 상태가 ongoing -> completed로 변경됩니다.
         *     모든 참여자의 WebSocket 연결이 종료됩니다.
         */
        post: operations["endMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회의 녹음 목록 조회
         * @description 특정 회의의 모든 녹음 목록을 조회합니다. 회의 참여자만 조회 가능합니다.
         */
        get: operations["getMeetingRecordings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/recordings/{recordingId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 녹음 다운로드 URL 조회
         * @description 특정 녹음의 다운로드 URL을 조회합니다.
         *     Presigned URL은 1시간 동안 유효합니다.
         *     회의 참여자만 다운로드 가능합니다.
         */
        get: operations["getRecordingDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/recordings/{recordingId}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 개별 녹음 트랜스크립트 조회
         * @description 특정 녹음의 STT 변환 결과를 조회합니다.
         */
        get: operations["getRecordingTranscript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/transcripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회의 전체 전사 조회 (Client → Backend)
         * @description 회의 ID를 기준으로 모든 전사 segment를 조회하고,
         *     createdAt 기준 시간 순서대로 정렬된 전체 전사 텍스트를 반환합니다.
         *     fullText는 서버에서 조립하며 DB에 저장되지 않습니다.
         */
        get: operations["getMeetingTranscripts"];
        put?: never;
        /**
         * 발화 segment 저장 (Worker → Backend)
         * @description Worker가 전송한 발화 segment를 DB에 저장합니다.
         *     path의 meeting_id와 body의 meetingId가 일치해야 합니다.
         */
        post: operations["createTranscriptSegment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회의 채팅 메시지 조회
         * @description 회의의 채팅 메시지를 시간순으로 조회합니다.
         *     - 페이지네이션 지원 (기본 100개, 최대 500개)
         *     - 오래된 메시지부터 정렬
         */
        get: operations["getChatMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description 에러 코드
             * @example VALIDATION_ERROR
             */
            error: string;
            /**
             * @description 에러 메시지
             * @example Invalid input data
             */
            message: string;
            /** @description 추가 에러 정보 */
            details?: {
                [key: string]: unknown;
            };
        };
        PaginationMeta: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 100 */
            total: number;
            /** @example 5 */
            totalPages: number;
        };
        /**
         * Format: uuid
         * @example 123e4567-e89b-12d3-a456-426614174000
         */
        UUID: string;
        /**
         * Format: date-time
         * @example 2024-12-31T12:00:00Z
         */
        Timestamp: string;
        /**
         * @description 인증 제공자 (네이버/구글 OAuth, 게스트)
         * @default naver
         * @enum {string}
         */
        AuthProvider: "naver" | "google" | "guest";
        User: {
            id: components["schemas"]["UUID"];
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example John Doe */
            name: string;
            authProvider: components["schemas"]["AuthProvider"];
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        NaverLoginUrlResponse: {
            /**
             * Format: uri
             * @description 네이버 OAuth 인증 URL
             */
            url: string;
        };
        GoogleLoginUrlResponse: {
            /**
             * Format: uri
             * @description Google OAuth 인증 URL
             */
            url: string;
        };
        TokenResponse: {
            /** @description JWT access token */
            accessToken: string;
            /** @description JWT refresh token */
            refreshToken: string;
            /**
             * @default Bearer
             * @enum {string}
             */
            tokenType: "Bearer";
            /**
             * @description Access token 만료 시간 (초)
             * @example 1800
             */
            expiresIn: number;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            tokens: components["schemas"]["TokenResponse"];
        };
        RefreshTokenRequest: {
            /** @description JWT refresh token */
            refreshToken: string;
        };
        /**
         * @description 팀 멤버 역할
         *     - owner: 팀 소유자 (팀 삭제, 설정 변경, 멤버 관리)
         *     - admin: 관리자 (멤버 관리, 회의 생성)
         *     - member: 일반 멤버 (회의 참여)
         * @enum {string}
         */
        TeamRole: "owner" | "admin" | "member";
        Team: {
            id: components["schemas"]["UUID"];
            /** @example Development Team */
            name: string;
            /** @example Backend development team */
            description?: string | null;
            createdBy: components["schemas"]["UUID"];
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        TeamMember: {
            id: components["schemas"]["UUID"];
            teamId: components["schemas"]["UUID"];
            userId: components["schemas"]["UUID"];
            user?: components["schemas"]["User"];
            role: components["schemas"]["TeamRole"];
            joinedAt: components["schemas"]["Timestamp"];
        };
        TeamWithMembers: components["schemas"]["Team"] & {
            members: components["schemas"]["TeamMember"][];
        };
        CreateTeamRequest: {
            /** @example Development Team */
            name: string;
            /** @example Backend development team */
            description?: string;
        };
        UpdateTeamRequest: {
            /** @example Development Team */
            name?: string;
            /** @example Backend development team */
            description?: string | null;
        };
        TeamListResponse: {
            items: components["schemas"]["Team"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /**
         * @description 회의 상태
         *     - scheduled: 예정됨
         *     - ongoing: 진행 중
         *     - completed: 완료됨
         *     - in_review: 회의록 검토 중 (Phase 2)
         *     - confirmed: 회의록 확정됨 (Phase 2)
         *     - cancelled: 취소됨
         * @enum {string}
         */
        MeetingStatus: "scheduled" | "ongoing" | "completed" | "in_review" | "confirmed" | "cancelled";
        /**
         * @description 회의 참여자 역할
         *     - host: 회의 주최자 (회의 수정/삭제, 참여자 관리)
         *     - participant: 참여자 (회의 참여, Review 권한)
         * @enum {string}
         */
        ParticipantRole: "host" | "participant";
        Meeting: {
            id: components["schemas"]["UUID"];
            teamId: components["schemas"]["UUID"];
            /** @example Weekly Standup */
            title: string;
            /** @example Weekly team standup meeting */
            description?: string | null;
            createdBy: components["schemas"]["UUID"];
            status: components["schemas"]["MeetingStatus"];
            scheduledAt?: components["schemas"]["Timestamp"];
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        MeetingParticipant: {
            id: components["schemas"]["UUID"];
            meetingId: components["schemas"]["UUID"];
            userId: components["schemas"]["UUID"];
            user?: components["schemas"]["User"];
            role: components["schemas"]["ParticipantRole"];
            joinedAt: components["schemas"]["Timestamp"];
        };
        MeetingWithParticipants: components["schemas"]["Meeting"] & {
            participants: components["schemas"]["MeetingParticipant"][];
        };
        CreateMeetingRequest: {
            /** @example Weekly Standup */
            title: string;
            /** @example Weekly team standup meeting */
            description?: string;
            /**
             * Format: date-time
             * @example 2024-12-31T14:00:00Z
             */
            scheduledAt?: string;
        };
        UpdateMeetingRequest: {
            /** @example Weekly Standup */
            title?: string;
            /** @example Weekly team standup meeting */
            description?: string | null;
            /** Format: date-time */
            scheduledAt?: string | null;
            status?: components["schemas"]["MeetingStatus"];
        };
        MeetingListResponse: {
            items: components["schemas"]["Meeting"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        InviteTeamMemberRequest: {
            /**
             * Format: email
             * @description 초대할 사용자의 이메일
             * @example newmember@example.com
             */
            email: string;
            /**
             * @description 멤버 역할 (기본값 member)
             * @default member
             */
            role: components["schemas"]["TeamRole"];
        };
        UpdateTeamMemberRequest: {
            /** @description 새로운 역할 */
            role: components["schemas"]["TeamRole"];
        };
        AddMeetingParticipantRequest: {
            /** @description 추가할 사용자의 ID */
            userId: components["schemas"]["UUID"];
            /**
             * @description 참여자 역할 (기본값 participant)
             * @default participant
             */
            role: components["schemas"]["ParticipantRole"];
        };
        UpdateMeetingParticipantRequest: {
            /** @description 새로운 역할 */
            role: components["schemas"]["ParticipantRole"];
        };
        RoomParticipant: {
            userId: components["schemas"]["UUID"];
            /** @example John Doe */
            userName: string;
            role: components["schemas"]["ParticipantRole"];
            /**
             * @description 오디오 음소거 상태
             * @default false
             */
            audioMuted: boolean;
        };
        IceServer: {
            /** @example stun:stun.l.google.com:19302 */
            urls: string;
            username?: string | null;
            credential?: string | null;
        };
        MeetingRoomResponse: {
            meetingId: components["schemas"]["UUID"];
            status: components["schemas"]["MeetingStatus"];
            participants: components["schemas"]["RoomParticipant"][];
            iceServers: components["schemas"]["IceServer"][];
            /**
             * @description 최대 참여자 수
             * @default 10
             */
            maxParticipants: number;
        };
        StartMeetingResponse: {
            meetingId: components["schemas"]["UUID"];
            status: components["schemas"]["MeetingStatus"];
            startedAt: components["schemas"]["Timestamp"];
        };
        EndMeetingResponse: {
            meetingId: components["schemas"]["UUID"];
            status: components["schemas"]["MeetingStatus"];
            endedAt: components["schemas"]["Timestamp"];
        };
        /**
         * @description 녹음 상태:
         *     - pending: 업로드 대기
         *     - recording: 녹음 중
         *     - completed: 녹음 완료
         *     - failed: 녹음 실패
         *     - transcribing: STT 변환 중
         *     - transcribed: STT 완료
         *     - transcription_failed: STT 실패
         * @enum {string}
         */
        RecordingStatus: "pending" | "recording" | "completed" | "failed" | "transcribing" | "transcribed" | "transcription_failed";
        Recording: {
            id: components["schemas"]["UUID"];
            meetingId: components["schemas"]["UUID"];
            /** @description 녹음한 사용자 ID (Server Recording은 null) */
            userId?: components["schemas"]["UUID"];
            userName?: string | null;
            status: components["schemas"]["RecordingStatus"];
            startedAt: components["schemas"]["Timestamp"];
            /** Format: date-time */
            endedAt?: string | null;
            /** @description 녹음 길이 (밀리초) */
            durationMs?: number | null;
            /** @description 파일 크기 (바이트) */
            fileSizeBytes?: number | null;
            createdAt: components["schemas"]["Timestamp"];
            /** @description STT 변환된 전체 텍스트 */
            transcriptText?: string | null;
            /** @description 감지된 언어 코드 (ko, en 등) */
            transcriptLanguage?: string | null;
            /**
             * Format: date-time
             * @description STT 변환 시작 시간
             */
            transcriptionStartedAt?: string | null;
            /**
             * Format: date-time
             * @description STT 변환 완료 시간
             */
            transcriptionCompletedAt?: string | null;
            /** @description STT 실패 시 에러 메시지 */
            transcriptionError?: string | null;
        };
        RecordingListResponse: {
            items: components["schemas"]["Recording"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        RecordingDownloadResponse: {
            recordingId: components["schemas"]["UUID"];
            /**
             * Format: uri
             * @description Presigned URL for downloading
             */
            downloadUrl: string;
            /**
             * @description URL 만료 시간 (초)
             * @default 3600
             */
            expiresInSeconds: number;
        };
        /** @description 채팅 메시지 */
        ChatMessage: {
            id: components["schemas"]["UUID"];
            meeting_id: components["schemas"]["UUID"];
            user_id: components["schemas"]["UUID"];
            /** @description 작성자 이름 */
            user_name: string;
            /** @description 메시지 내용 (Markdown 지원) */
            content: string;
            created_at: components["schemas"]["Timestamp"];
        };
        /** @description 채팅 메시지 목록 응답 */
        ChatMessageListResponse: {
            messages: components["schemas"]["ChatMessage"][];
            /** @description 전체 메시지 수 */
            total: number;
            /** @description 현재 페이지 */
            page: number;
            /** @description 페이지당 메시지 수 */
            limit: number;
        };
        UtteranceItem: {
            /** @description Transcript segment ID */
            id: components["schemas"]["UUID"];
            /** @description 발화자 ID */
            speakerId: components["schemas"]["UUID"];
            /** @description 발화자 이름 (user가 없으면 "Unknown") */
            speakerName: string;
            /** @description 발화 시작 시간 (밀리초) */
            startMs: number;
            /** @description 발화 종료 시간 (밀리초) */
            endMs: number;
            /** @description 발화 텍스트 */
            text: string;
            /** @description segment 생성 시간 */
            timestamp: components["schemas"]["Timestamp"];
        };
        GetMeetingTranscriptsResponse: {
            /** @description 회의 ID */
            meetingId: components["schemas"]["UUID"];
            /**
             * @description 트랜스크립트 상태 (현재는 항상 completed)
             * @enum {string}
             */
            status: "completed";
            /**
             * @description 전체 전사 텍스트 (서버에서 조립)
             *     형식: "{speakerName}: {text}\n..."
             */
            fullText: string;
            /** @description 개별 발화 목록 (createdAt 기준 ASC 정렬) */
            utterances: components["schemas"]["UtteranceItem"][];
            /** @description 전체 길이 (가장 큰 endMs 값) */
            totalDurationMs: number;
            /** @description 고유 발화자 수 */
            speakerCount: number;
            /**
             * Format: date-time
             * @description 회의 시작 시간 (현재 null)
             */
            meetingStart?: string | null;
            /**
             * Format: date-time
             * @description 회의 종료 시간 (현재 null)
             */
            meetingEnd?: string | null;
            /** @description 첫 번째 transcript 생성 시간 */
            createdAt: components["schemas"]["Timestamp"];
        };
        CreateTranscriptRequest: {
            /** @description 회의 ID (path parameter와 일치해야 함) */
            meetingId: components["schemas"]["UUID"];
            /** @description 발화자 ID */
            userId: components["schemas"]["UUID"];
            /** @description 발화 시작 시간 (밀리초) */
            startMs: number;
            /** @description 발화 종료 시간 (밀리초, startMs보다 커야 함) */
            endMs: number;
            /** @description 전사된 텍스트 */
            text: string;
            /**
             * Format: float
             * @description 평균 신뢰도
             */
            confidence: number;
            /**
             * Format: float
             * @description 최소 신뢰도
             */
            minConfidence: number;
            /**
             * @description 에이전트 호출 여부
             * @default false
             */
            agentCall: boolean;
            /** @description 에이전트 호출 키워드 */
            agentCallKeyword?: string | null;
            /**
             * Format: float
             * @description 에이전트 호출 키워드 신뢰도
             */
            agentCall_confidence?: number | null;
        };
        CreateTranscriptResponse: {
            /** @description 생성된 transcript segment ID */
            id: components["schemas"]["UUID"];
            /** @description 생성 시간 */
            createdAt: components["schemas"]["Timestamp"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getNaverLoginUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 네이버 OAuth URL 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NaverLoginUrlResponse"];
                };
            };
        };
    };
    naverCallback: {
        parameters: {
            query: {
                /** @description 네이버에서 전달받은 인증 코드 */
                code: string;
                /** @description CSRF 방지용 상태 토큰 */
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description 유효하지 않은 인증 코드 또는 상태 토큰 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGoogleLoginUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Google OAuth URL 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleLoginUrlResponse"];
                };
            };
        };
    };
    googleCallback: {
        parameters: {
            query: {
                /** @description Google에서 전달받은 인증 코드 */
                code: string;
                /** @description CSRF 방지용 상태 토큰 */
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description 유효하지 않은 인증 코드 또는 상태 토큰 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    guestLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 게스트 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description 서버 에러 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description 토큰 갱신 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description 유효하지 않은 refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 사용자 정보 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listMyTeams: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 팀 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamListResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description 팀 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 팀 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamWithMembers"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamRequest"];
            };
        };
        responses: {
            /** @description 팀 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 팀 삭제 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (owner만 삭제 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listTeamMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 멤버 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"][];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    inviteTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteTeamMemberRequest"];
            };
        };
        responses: {
            /** @description 멤버 초대 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (owner 또는 admin만 초대 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀 또는 사용자를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 팀 멤버임 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateTeamMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamMemberRequest"];
            };
        };
        responses: {
            /** @description 역할 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (owner만 수정 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀 또는 멤버를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 멤버 제거 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀 또는 멤버를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listTeamMeetings: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description 회의 상태로 필터링 */
                status?: components["schemas"]["MeetingStatus"];
            };
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회의 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingListResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMeetingRequest"];
            };
        };
        responses: {
            /** @description 회의 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (팀 멤버만 생성 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회의 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingWithParticipants"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeetingRequest"];
            };
        };
        responses: {
            /** @description 회의 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회의 삭제 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listMeetingParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 참여자 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingParticipant"][];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addMeetingParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMeetingParticipantRequest"];
            };
        };
        responses: {
            /** @description 참여자 추가 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingParticipant"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (host만 추가 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의 또는 사용자를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 참여자임 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateMeetingParticipantRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeetingParticipantRequest"];
            };
        };
        responses: {
            /** @description 역할 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingParticipant"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (host만 수정 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의 또는 참여자를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeMeetingParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 참여자 제거 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의 또는 참여자를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMeetingRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회의실 정보 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRoomResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (회의 참여자만 조회 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회의 시작 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartMeetingResponse"];
                };
            };
            /** @description 이미 진행 중이거나 종료된 회의 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (host만 시작 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    endMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회의 종료 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndMeetingResponse"];
                };
            };
            /** @description 진행 중인 회의가 아님 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (host만 종료 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMeetingRecordings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 녹음 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingListResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (참여자가 아님) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecordingDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
                recordingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 다운로드 URL 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDownloadResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (참여자가 아님) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의 또는 녹음을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 스토리지 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecordingTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
                recordingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 트랜스크립트 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 녹음을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMeetingTranscripts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 회의 ID */
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMeetingTranscriptsResponse"];
                };
            };
            /** @description Meeting을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "MEETING_NOT_FOUND",
                     *       "message": "회의를 찾을 수 없습니다."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 내부 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "INTERNAL_ERROR",
                     *       "message": "서버 오류가 발생했습니다."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createTranscriptSegment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 회의 ID */
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTranscriptRequest"];
            };
        };
        responses: {
            /** @description Segment 저장 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "550e8400-e29b-41d4-a716-446655440000",
                     *       "createdAt": "2026-01-23T10:30:45.123456Z"
                     *     }
                     */
                    "application/json": components["schemas"]["CreateTranscriptResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Meeting을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "MEETING_NOT_FOUND",
                     *       "message": "회의를 찾을 수 없습니다."
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation 오류 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": [
                     *         {
                     *           "type": "string_too_short",
                     *           "loc": [
                     *             "body",
                     *             "text"
                     *           ],
                     *           "msg": "String should have at least 1 character"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        detail?: Record<string, never>[];
                    };
                };
            };
        };
    };
    getChatMessages: {
        parameters: {
            query?: {
                /** @description 페이지 번호 */
                page?: number;
                /** @description 페이지당 메시지 수 */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description 회의 ID */
                meetingId: components["schemas"]["UUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 채팅 메시지 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageListResponse"];
                };
            };
            /** @description 인증되지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의 참여자가 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
