/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 이메일/비밀번호로 새 계정을 생성합니다.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일/비밀번호로 로그인합니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 갱신
         * @description Refresh token으로 새 access token을 발급받습니다.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 현재 세션을 종료합니다 (refresh token 무효화).
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 사용자 정보
         * @description 현재 로그인한 사용자의 정보를 조회합니다.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 팀 목록
         * @description 현재 사용자가 속한 팀 목록을 조회합니다.
         */
        get: operations["listMyTeams"];
        put?: never;
        /**
         * 팀 생성
         * @description 새로운 팀을 생성합니다. 생성자는 자동으로 owner가 됩니다.
         */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{teamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 상세 조회
         * @description 팀 상세 정보를 조회합니다. 팀 멤버만 조회 가능합니다.
         */
        get: operations["getTeam"];
        /**
         * 팀 수정
         * @description 팀 정보를 수정합니다. owner 또는 admin만 수정 가능합니다.
         */
        put: operations["updateTeam"];
        post?: never;
        /**
         * 팀 삭제
         * @description 팀을 삭제합니다. owner만 삭제 가능합니다.
         */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{teamId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 멤버 목록
         * @description 팀의 멤버 목록을 조회합니다. 팀 멤버만 조회 가능합니다.
         */
        get: operations["listTeamMembers"];
        put?: never;
        /**
         * 팀 멤버 초대
         * @description 팀에 새로운 멤버를 초대합니다. owner 또는 admin만 초대 가능합니다.
         */
        post: operations["inviteTeamMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{teamId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 멤버 역할 수정
         * @description 팀 멤버의 역할을 수정합니다. owner만 수정 가능합니다.
         */
        put: operations["updateTeamMemberRole"];
        post?: never;
        /**
         * 멤버 제거
         * @description 팀에서 멤버를 제거합니다. owner 또는 admin만 제거 가능합니다. 자신을 제거하는 것은 항상 가능합니다.
         */
        delete: operations["removeTeamMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{teamId}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 회의 목록
         * @description 팀의 회의 목록을 조회합니다.
         */
        get: operations["listTeamMeetings"];
        put?: never;
        /**
         * 회의 생성
         * @description 팀에 새로운 회의를 생성합니다. 생성자는 자동으로 host가 됩니다.
         */
        post: operations["createMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회의 상세 조회
         * @description 회의 상세 정보를 조회합니다. 팀 멤버만 조회 가능합니다.
         */
        get: operations["getMeeting"];
        /**
         * 회의 수정
         * @description 회의 정보를 수정합니다. host 또는 팀 owner/admin만 수정 가능합니다.
         */
        put: operations["updateMeeting"];
        post?: never;
        /**
         * 회의 삭제
         * @description 회의를 삭제합니다. host 또는 팀 owner/admin만 삭제 가능합니다.
         */
        delete: operations["deleteMeeting"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회의 참여자 목록
         * @description 회의의 참여자 목록을 조회합니다. 팀 멤버만 조회 가능합니다.
         */
        get: operations["listMeetingParticipants"];
        put?: never;
        /**
         * 회의 참여자 추가
         * @description 회의에 새로운 참여자를 추가합니다. host만 추가 가능합니다. 해당 팀의 멤버만 추가할 수 있습니다.
         */
        post: operations["addMeetingParticipant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/participants/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 참여자 역할 수정
         * @description 회의 참여자의 역할을 수정합니다. host만 수정 가능합니다.
         */
        put: operations["updateMeetingParticipantRole"];
        post?: never;
        /**
         * 참여자 제거
         * @description 회의에서 참여자를 제거합니다. host만 제거 가능합니다. 자신을 제거하는 것은 항상 가능합니다.
         */
        delete: operations["removeMeetingParticipant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description 에러 코드
             * @example VALIDATION_ERROR
             */
            error: string;
            /**
             * @description 에러 메시지
             * @example Invalid input data
             */
            message: string;
            /** @description 추가 에러 정보 */
            details?: {
                [key: string]: unknown;
            };
        };
        PaginationMeta: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 100 */
            total: number;
            /** @example 5 */
            totalPages: number;
        };
        /**
         * Format: uuid
         * @example 123e4567-e89b-12d3-a456-426614174000
         */
        UUID: string;
        /**
         * Format: date-time
         * @example 2024-12-31T12:00:00Z
         */
        Timestamp: string;
        /**
         * @description 인증 제공자
         * @default local
         * @enum {string}
         */
        AuthProvider: "local" | "google" | "github";
        User: {
            id: components["schemas"]["UUID"];
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example John Doe */
            name: string;
            authProvider: components["schemas"]["AuthProvider"];
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        RegisterRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @example securePassword123
             */
            password: string;
            /** @example John Doe */
            name: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @example securePassword123
             */
            password: string;
        };
        TokenResponse: {
            /** @description JWT access token */
            accessToken: string;
            /** @description JWT refresh token */
            refreshToken: string;
            /**
             * @default Bearer
             * @enum {string}
             */
            tokenType: "Bearer";
            /**
             * @description Access token 만료 시간 (초)
             * @example 1800
             */
            expiresIn: number;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            tokens: components["schemas"]["TokenResponse"];
        };
        RefreshTokenRequest: {
            /** @description JWT refresh token */
            refreshToken: string;
        };
        /**
         * @description 팀 멤버 역할
         *     - owner: 팀 소유자 (팀 삭제, 설정 변경, 멤버 관리)
         *     - admin: 관리자 (멤버 관리, 회의 생성)
         *     - member: 일반 멤버 (회의 참여)
         * @enum {string}
         */
        TeamRole: "owner" | "admin" | "member";
        Team: {
            id: components["schemas"]["UUID"];
            /** @example Development Team */
            name: string;
            /** @example Backend development team */
            description?: string | null;
            createdBy: components["schemas"]["UUID"];
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        TeamMember: {
            id: components["schemas"]["UUID"];
            teamId: components["schemas"]["UUID"];
            userId: components["schemas"]["UUID"];
            user?: components["schemas"]["User"];
            role: components["schemas"]["TeamRole"];
            joinedAt: components["schemas"]["Timestamp"];
        };
        TeamWithMembers: {
            id: components["schemas"]["UUID"];
            /** @example Development Team */
            name: string;
            /** @example Backend development team */
            description?: string | null;
            createdBy: components["schemas"]["UUID"];
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
            members: components["schemas"]["TeamMember"][];
        };
        CreateTeamRequest: {
            /** @example Development Team */
            name: string;
            /** @example Backend development team */
            description?: string;
        };
        UpdateTeamRequest: {
            /** @example Development Team */
            name?: string;
            /** @example Backend development team */
            description?: string | null;
        };
        TeamListResponse: {
            items: components["schemas"]["Team"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /**
         * @description 회의 상태
         *     - scheduled: 예정됨
         *     - ongoing: 진행 중
         *     - completed: 완료됨
         *     - in_review: 회의록 검토 중 (Phase 2)
         *     - confirmed: 회의록 확정됨 (Phase 2)
         *     - cancelled: 취소됨
         * @enum {string}
         */
        MeetingStatus: "scheduled" | "ongoing" | "completed" | "in_review" | "confirmed" | "cancelled";
        /**
         * @description 회의 참여자 역할
         *     - host: 회의 주최자 (회의 수정/삭제, 참여자 관리)
         *     - participant: 참여자 (회의 참여, Review 권한)
         * @enum {string}
         */
        ParticipantRole: "host" | "participant";
        Meeting: {
            id: components["schemas"]["UUID"];
            teamId: components["schemas"]["UUID"];
            /** @example Weekly Standup */
            title: string;
            /** @example Weekly team standup meeting */
            description?: string | null;
            createdBy: components["schemas"]["UUID"];
            status: components["schemas"]["MeetingStatus"];
            scheduledAt?: components["schemas"]["Timestamp"];
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        MeetingParticipant: {
            id: components["schemas"]["UUID"];
            meetingId: components["schemas"]["UUID"];
            userId: components["schemas"]["UUID"];
            user?: components["schemas"]["User"];
            role: components["schemas"]["ParticipantRole"];
            joinedAt: components["schemas"]["Timestamp"];
        };
        MeetingWithParticipants: {
            id: components["schemas"]["UUID"];
            teamId: components["schemas"]["UUID"];
            /** @example Weekly Standup */
            title: string;
            /** @example Weekly team standup meeting */
            description?: string | null;
            createdBy: components["schemas"]["UUID"];
            status: components["schemas"]["MeetingStatus"];
            scheduledAt?: components["schemas"]["Timestamp"];
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
            participants: components["schemas"]["MeetingParticipant"][];
        };
        CreateMeetingRequest: {
            /** @example Weekly Standup */
            title: string;
            /** @example Weekly team standup meeting */
            description?: string;
            /**
             * Format: date-time
             * @example 2024-12-31T14:00:00Z
             */
            scheduledAt?: string;
        };
        UpdateMeetingRequest: {
            /** @example Weekly Standup */
            title?: string;
            /** @example Weekly team standup meeting */
            description?: string | null;
            /** Format: date-time */
            scheduledAt?: string | null;
            status?: components["schemas"]["MeetingStatus"];
        };
        MeetingListResponse: {
            items: components["schemas"]["Meeting"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        InviteTeamMemberRequest: {
            /**
             * Format: email
             * @description 초대할 사용자의 이메일
             * @example newmember@example.com
             */
            email: string;
            /**
             * @description 멤버 역할 (기본값 member)
             * @default member
             */
            role: components["schemas"]["TeamRole"];
        };
        UpdateTeamMemberRequest: {
            /** @description 새로운 역할 */
            role: components["schemas"]["TeamRole"];
        };
        AddMeetingParticipantRequest: {
            /** @description 추가할 사용자의 ID */
            userId: components["schemas"]["UUID"];
            /**
             * @description 참여자 역할 (기본값 participant)
             * @default participant
             */
            role: components["schemas"]["ParticipantRole"];
        };
        UpdateMeetingParticipantRequest: {
            /** @description 새로운 역할 */
            role: components["schemas"]["ParticipantRole"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 회원가입 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 존재하는 이메일 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description 토큰 갱신 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description 유효하지 않은 refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 사용자 정보 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listMyTeams: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 팀 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamListResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description 팀 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 팀 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamWithMembers"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamRequest"];
            };
        };
        responses: {
            /** @description 팀 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 팀 삭제 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (owner만 삭제 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listTeamMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 멤버 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"][];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    inviteTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteTeamMemberRequest"];
            };
        };
        responses: {
            /** @description 멤버 초대 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (owner 또는 admin만 초대 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀 또는 사용자를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 팀 멤버임 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateTeamMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamMemberRequest"];
            };
        };
        responses: {
            /** @description 역할 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (owner만 수정 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀 또는 멤버를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 멤버 제거 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀 또는 멤버를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listTeamMeetings: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description 회의 상태로 필터링 */
                status?: components["schemas"]["MeetingStatus"];
            };
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회의 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingListResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMeetingRequest"];
            };
        };
        responses: {
            /** @description 회의 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (팀 멤버만 생성 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 팀을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회의 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingWithParticipants"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeetingRequest"];
            };
        };
        responses: {
            /** @description 회의 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회의 삭제 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listMeetingParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 참여자 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingParticipant"][];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addMeetingParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMeetingParticipantRequest"];
            };
        };
        responses: {
            /** @description 참여자 추가 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingParticipant"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (host만 추가 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의 또는 사용자를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 참여자임 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateMeetingParticipantRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeetingParticipantRequest"];
            };
        };
        responses: {
            /** @description 역할 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingParticipant"];
                };
            };
            /** @description 유효하지 않은 입력 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 (host만 수정 가능) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의 또는 참여자를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeMeetingParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 참여자 제거 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 회의 또는 참여자를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
