"""add vad_segments to meeting_recordings

Revision ID: 56401abb2fd4
Revises: d4e5f6g7h8i9
Create Date: 2026-01-13 21:07:46.952063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56401abb2fd4'
down_revision: Union[str, None] = 'd4e5f6g7h8i9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_recordings', sa.Column('vad_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='클라이언트에서 감지한 VAD 발화 구간 JSON'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_recordings', 'vad_segments')
    # ### end Alembic commands ###
