"""

Revision ID: 738f30c0e1d2
Revises: 8d812817ec16
Create Date: 2026-02-04 13:57:41.026129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '738f30c0e1d2'
down_revision: Union[str, None] = '8d812817ec16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS checkpoints_thread_id_idx')
    op.execute('DROP TABLE IF EXISTS checkpoints')
    op.execute('DROP INDEX IF EXISTS checkpoint_writes_thread_id_idx')
    op.execute('DROP TABLE IF EXISTS checkpoint_writes')
    op.execute('DROP INDEX IF EXISTS checkpoint_blobs_thread_id_idx')
    op.execute('DROP TABLE IF EXISTS checkpoint_blobs')
    op.execute('DROP TABLE IF EXISTS meeting_transcripts')
    op.execute('DROP TABLE IF EXISTS meeting_recordings')
    op.execute('DROP TABLE IF EXISTS checkpoint_migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('meeting_recordings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True, comment='녹음한 사용자 ID (Composite 녹음은 NULL)'),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('transcript_text', sa.TEXT(), autoincrement=False, nullable=True, comment='STT 변환된 전체 텍스트'),
    sa.Column('transcript_segments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='타임스탬프 포함 세그먼트 JSON'),
    sa.Column('transcript_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='감지된 언어 코드 (ko, en 등)'),
    sa.Column('transcription_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transcription_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transcription_error', sa.TEXT(), autoincrement=False, nullable=True, comment='STT 실패 시 에러 메시지'),
    sa.Column('vad_segments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='클라이언트에서 감지한 VAD 발화 구간 JSON'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('meeting_recordings_meeting_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('meeting_recordings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meeting_recordings_pkey'))
    )
    op.create_table('meeting_transcripts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True, comment='전체 텍스트 (화자 라벨 포함)'),
    sa.Column('utterances', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='화자별 발화 목록'),
    sa.Column('total_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speaker_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True, comment='실패 시 에러 메시지'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='MinIO에 저장된 회의록 파일 경로'),
    sa.Column('meeting_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='회의 실제 시작 시각'),
    sa.Column('meeting_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='회의 실제 종료 시각'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('meeting_transcripts_meeting_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meeting_transcripts_pkey')),
    sa.UniqueConstraint('meeting_id', name=op.f('meeting_transcripts_meeting_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    # ### end Alembic commands ###
