"""add meeting_start and meeting_end to transcript

Revision ID: a568e7cad9bd
Revises: 56401abb2fd4
Create Date: 2026-01-14 15:19:06.950739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a568e7cad9bd'
down_revision: Union[str, None] = '56401abb2fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_transcripts', sa.Column('meeting_start', sa.DateTime(timezone=True), nullable=True, comment='회의 실제 시작 시각'))
    op.add_column('meeting_transcripts', sa.Column('meeting_end', sa.DateTime(timezone=True), nullable=True, comment='회의 실제 종료 시각'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_transcripts', 'meeting_end')
    op.drop_column('meeting_transcripts', 'meeting_start')
    # ### end Alembic commands ###
