"""add_user_activity_logs

Revision ID: e5f6g7h8i9j0
Revises: fa12da308ae8
Create Date: 2026-02-04 05:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID


# revision identifiers, used by Alembic.
revision: str = 'e5f6g7h8i9j0'
down_revision: Union[str, None] = 'fa12da308ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_activity_logs',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', UUID(as_uuid=True), nullable=True),
        sa.Column('session_id', sa.String(length=64), nullable=False),
        sa.Column('event_type', sa.String(length=32), nullable=False),
        sa.Column('event_target', sa.String(length=512), nullable=True),
        sa.Column('page_path', sa.String(length=255), nullable=False),
        sa.Column('event_metadata', JSONB, nullable=True),
        sa.Column('user_agent', sa.String(length=512), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_logs_session_id'), 'user_activity_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_event_type'), 'user_activity_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_page_path'), 'user_activity_logs', ['page_path'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_created_at'), 'user_activity_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activity_logs_created_at'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_page_path'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_event_type'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_session_id'), table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    # ### end Alembic commands ###
