"""make recording user_id nullable for composite recordings

Revision ID: fa12da308ae8
Revises: a568e7cad9bd
Create Date: 2026-01-19 15:20:26.804673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa12da308ae8'
down_revision: Union[str, None] = 'a568e7cad9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting_recordings', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='녹음한 사용자 ID (Composite 녹음은 NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting_recordings', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='녹음한 사용자 ID (Composite 녹음은 NULL)')
    # ### end Alembic commands ###
