"""Generate PR 워크플로우 프롬프트 — 2단계 파이프라인"""

from .extraction import (
    KEYWORD_EXTRACTION_PROMPT,
    KEYWORD_EXTRACTION_SCHEMA,
    MINUTES_GENERATION_PROMPT,
    MINUTES_GENERATION_SCHEMA,
    VERSION,
)

__all__ = [
    "VERSION",
    "KEYWORD_EXTRACTION_PROMPT",
    "KEYWORD_EXTRACTION_SCHEMA",
    "MINUTES_GENERATION_PROMPT",
    "MINUTES_GENERATION_SCHEMA",
]
